server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 默认参数配置
analysis.default.price-percentile=30
analysis.default.time-percentile=20
analysis.default.sell-price-multiple=3
